# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker: 
      - image: circleci/node:13.8.0     
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyse:
    docker: 
      - image: circleci/node:13.8.0     
    steps:  
      - checkout
      - run: npm i
      - run: npm audit
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-env-vars:
    jobs:
      - build
      - test:
        requires:
          - build
      - analyse:
        requires:
          - test
      